# Generated by Django 4.2.1 on 2023-05-15 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('idocena', models.AutoField(db_column='IdOcena', primary_key=True, serialize=False)),
                ('ocena', models.IntegerField()),
            ],
            options={
                'db_table': 'ocena',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oglas',
            fields=[
                ('idoglas', models.AutoField(db_column='IdOglas', primary_key=True, serialize=False)),
                ('sport', models.CharField(db_column='Sport', max_length=20)),
                ('vreme', models.TimeField()),
                ('datum', models.DateField()),
                ('brigraca', models.IntegerField(db_column='BrIgraca')),
                ('lokacija', models.CharField(db_column='Lokacija', max_length=20)),
                ('gotov', models.IntegerField(db_column='Gotov')),
            ],
            options={
                'db_table': 'oglas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrijaveOrganizatora',
            fields=[
                ('idprijave', models.AutoField(db_column='IdPrijave', primary_key=True, serialize=False)),
                ('mail', models.CharField(max_length=64, unique=True)),
                ('ime', models.CharField(db_column='Ime', max_length=20)),
                ('prezime', models.CharField(db_column='Prezime', max_length=20)),
                ('telefon', models.CharField(max_length=20)),
                ('datum', models.DateField()),
                ('pol', models.IntegerField()),
                ('jmbg', models.CharField(db_column='JMBG', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'prijave_organizatora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('iduser', models.AutoField(db_column='IdUser', primary_key=True, serialize=False)),
                ('mail', models.CharField(max_length=64, unique=True)),
                ('ime', models.CharField(db_column='Ime', max_length=20)),
                ('prezime', models.CharField(db_column='Prezime', max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('telefon', models.CharField(max_length=20)),
                ('datum', models.DateField()),
                ('pol', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('idadmin', models.OneToOneField(db_column='IdAdmin', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tad.user')),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('idkor', models.OneToOneField(db_column='IdKor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tad.user')),
                ('nivo', models.IntegerField(db_column='Nivo')),
            ],
            options={
                'db_table': 'korisnik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organizator',
            fields=[
                ('idorg', models.OneToOneField(db_column='IdOrg', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tad.user')),
                ('jmbg', models.CharField(db_column='JMBG', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'organizator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrijaveZaOglas',
            fields=[
                ('status', models.IntegerField()),
                ('idoglas', models.OneToOneField(db_column='IdOglas', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tad.oglas')),
            ],
            options={
                'db_table': 'prijave_za_oglas',
                'managed': False,
            },
        ),
    ]
